name: SonarCloud CI
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build-and-analyze:
    name: Build & Analyze Monorepo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "zulu"

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install frontend deps
        working-directory: Frontend
        run: |
          npm install
          npm run build

      - name: Build backend
        working-directory: Backend/PASiR_Kamil_Lenczyk
        run: mvn clean install -DskipTests

      - name: Cache SonarCloud
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: ${{ github.workspace }}
          args: >
            -Dsonar.projectKey=BiorA3_fullstack-app
            -Dsonar.organization=biora3-1
            -Dsonar.projectName=BudgetApp
            -Dsonar.projectVersion=1.0
            -Dsonar.modules=PASiR_Kamil_Lenczyk,Frontend
            -Dsonar.frontend.projectName=Frontend
            -Dsonar.frontend.projectBaseDir=Frontend
            -Dsonar.frontend.sources=src
            -Dsonar.frontend.exclusions=**/*.spec.ts,**/*.test.tsx,**/__tests__/**
            -Dsonar.frontend.typescript.tsconfigPath=Frontend/tsconfig.json
            -Dsonar.backend.projectName=Backend
            -Dsonar.backend.projectBaseDir=Backend/PASiR_Kamil_Lenczyk
            -Dsonar.backend.sources=src/main
            -Dsonar.backend.java.binaries=target/classes
            -Dsonar.backend.java.source=11

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
